/**
 * Test suite for Professional Reporting Service - Phase 4 TDD Implementation
 * 
 * Tests for professional consultation reports, billing analysis, and documentation
 * Following TDD: Write failing tests first, then implement to make them pass
 */

import { describe, it, expect, beforeEach, vi } from 'vitest';

// Mock jsPDF and html2canvas
vi.mock('jspdf', () => ({
  default: vi.fn().mockImplementation(() => ({
    addImage: vi.fn(),
    addPage: vi.fn(),
    output: vi.fn().mockReturnValue(new Blob(['mock pdf'], { type: 'application/pdf' }))
  }))
}));

vi.mock('html2canvas', () => ({
  default: vi.fn().mockResolvedValue({
    toDataURL: vi.fn().mockReturnValue('data:image/png;base64,mock-image-data'),
    width: 794,
    height: 1123
  })
}));

vi.mock('file-saver', () => ({
  saveAs: vi.fn()
}));

vi.mock('xlsx', () => ({
  utils: {
    book_new: vi.fn().mockReturnValue({}),
    aoa_to_sheet: vi.fn().mockReturnValue({}),
    book_append_sheet: vi.fn()
  },
  write: vi.fn().mockReturnValue(new ArrayBuffer(8))
}));
import {
  ReportingService,
  generateConsultationReport,
  generateBillingAnalysisReport,
  generateConflictReport,
  generateRecommendationReport
} from './reportingService';
import {
  ReportConfiguration,
  EnhancedCodeRecommendation,
  SelectionState,
  MBSCategory,
  ExportData
} from '../types/api.types';

describe('ReportingService', () => {
  let mockRecommendations: EnhancedCodeRecommendation[];
  let mockSelectionState: SelectionState;
  let mockConsultationNote: string;
  let reportingService: ReportingService;

  beforeEach(() => {
    mockConsultationNote = `Patient presents with chest pain and shortness of breath. 
    History of hypertension and diabetes. Physical examination reveals irregular heart rhythm.
    ECG shows atrial fibrillation. Blood pressure elevated at 180/100.
    Recommended cardiac monitoring and medication adjustment.`;

    mockRecommendations = [
      {
        code: '23',
        description: 'Level A consultation - new patient',
        confidence: 0.9,
        schedule_fee: 41.20,
        category: '1',
        conflicts: [],
        compatibleWith: ['110', '57'],
        mbsCategory: 'professional_attendances' as MBSCategory,
        timeRequirement: 20,
        reasoning: 'Standard consultation appropriate for new patient assessment',
        evidence_spans: [
          { start: 0, end: 25, text: 'Patient presents with', relevance: 0.8 }
        ]
      },
      {
        code: '110',
        description: 'ECG recording and report',
        confidence: 0.95,
        schedule_fee: 19.80,
        category: '5',
        conflicts: [],
        compatibleWith: ['23', '36'],
        mbsCategory: 'diagnostic_procedures' as MBSCategory,
        timeRequirement: 10,
        reasoning: 'ECG clearly indicated for cardiac assessment',
        evidence_spans: [
          { start: 150, end: 175, text: 'ECG shows atrial fibrillation', relevance: 0.95 }
        ]
      },
      {
        code: '57',
        description: 'Blood pressure monitoring',
        confidence: 0.85,
        schedule_fee: 15.50,
        category: '2',
        conflicts: [],
        compatibleWith: ['23', '110'],
        mbsCategory: 'diagnostic_procedures' as MBSCategory,
        timeRequirement: 5,
        reasoning: 'Blood pressure monitoring indicated for hypertension',
        evidence_spans: [
          { start: 200, end: 230, text: 'Blood pressure elevated at 180/100', relevance: 0.9 }
        ]
      }
    ];

    mockSelectionState = {
      selectedCodes: new Set(['23', '110', '57']),
      conflicts: new Map(),
      totalFee: 76.50,
      warnings: []
    };

    reportingService = new ReportingService();
  });

  describe('generateConsultationReport', () => {
    it('should generate a complete consultation report', () => {
      const config: ReportConfiguration = {
        type: 'consultation_summary',
        sections: {
          summary: true,
          codeDetails: true,
          conflicts: true,
          recommendations: true,
          evidence: true,
          billing: true
        },
        styling: {
          template: 'professional',
          headerText: 'Medical Consultation Report',
          footerText: 'Generated by MBS RAG System'
        }
      };

      const report = generateConsultationReport(
        mockSelectionState,
        mockRecommendations,
        mockConsultationNote,
        'general_practice',
        config
      );

      expect(report).toHaveProperty('title', 'Medical Consultation Report');
      expect(report).toHaveProperty('sections');
      expect(report).toHaveProperty('metadata');
      expect(report).toHaveProperty('generatedAt');
      expect(report.sections).toHaveProperty('summary');
      expect(report.sections).toHaveProperty('consultationDetails');
      expect(report.sections).toHaveProperty('selectedCodes');
      expect(report.sections).toHaveProperty('billingInformation');
    });

    it('should include consultation summary section', () => {
      const config: ReportConfiguration = {
        type: 'consultation_summary',
        sections: {
          summary: true,
          codeDetails: false,
          conflicts: false,
          recommendations: false,
          evidence: false,
          billing: false
        },
        styling: { template: 'simple' }
      };

      const report = generateConsultationReport(
        mockSelectionState,
        mockRecommendations,
        mockConsultationNote,
        'general_practice',
        config
      );

      expect(report.sections.summary).toBeDefined();
      expect(report.sections.summary.totalCodes).toBe(3);
      expect(report.sections.summary.totalFee).toBe(76.50);
      expect(report.sections.summary.consultationContext).toBe('general_practice');
      expect(report.sections.summary.conflictsDetected).toBe(false);
    });

    it('should include detailed code information when requested', () => {
      const config: ReportConfiguration = {
        type: 'consultation_summary',
        sections: {
          summary: false,
          codeDetails: true,
          conflicts: false,
          recommendations: false,
          evidence: false,
          billing: false
        },
        styling: { template: 'detailed' }
      };

      const report = generateConsultationReport(
        mockSelectionState,
        mockRecommendations,
        mockConsultationNote,
        'general_practice',
        config
      );

      expect(report.sections.selectedCodes).toBeDefined();
      expect(report.sections.selectedCodes).toHaveLength(3);
      
      const ecgCode = report.sections.selectedCodes.find(c => c.code === '110');
      expect(ecgCode).toBeDefined();
      expect(ecgCode!.description).toBe('ECG recording and report');
      expect(ecgCode!.scheduleFee).toBe(19.80);
      expect(ecgCode!.confidence).toBe(0.95);
    });

    it('should include evidence spans when requested', () => {
      const config: ReportConfiguration = {
        type: 'consultation_summary',
        sections: {
          summary: false,
          codeDetails: false,
          conflicts: false,
          recommendations: false,
          evidence: true,
          billing: false
        },
        styling: { template: 'detailed' }
      };

      const report = generateConsultationReport(
        mockSelectionState,
        mockRecommendations,
        mockConsultationNote,
        'general_practice',
        config
      );

      expect(report.sections.evidenceSupport).toBeDefined();
      expect(report.sections.evidenceSupport).toHaveLength(3);
      
      const ecgEvidence = report.sections.evidenceSupport.find(e => e.code === '110');
      expect(ecgEvidence).toBeDefined();
      expect(ecgEvidence!.evidenceSpans).toHaveLength(1);
      expect(ecgEvidence!.evidenceSpans[0].text).toBe('ECG shows atrial fibrillation');
    });

    it('should include billing breakdown when requested', () => {
      const config: ReportConfiguration = {
        type: 'consultation_summary',
        sections: {
          summary: false,
          codeDetails: false,
          conflicts: false,
          recommendations: false,
          evidence: false,
          billing: true
        },
        styling: { template: 'professional' }
      };

      const report = generateConsultationReport(
        mockSelectionState,
        mockRecommendations,
        mockConsultationNote,
        'general_practice',
        config
      );

      expect(report.sections.billingInformation).toBeDefined();
      expect(report.sections.billingInformation.subtotal).toBe(76.50);
      expect(report.sections.billingInformation.itemizedCharges).toHaveLength(3);
      expect(report.sections.billingInformation.itemizedCharges.some(item => 
        item.code === '23' && item.fee === 41.20
      )).toBe(true);
    });

    it('should handle conflicts in consultation report', () => {
      const conflictedSelectionState: SelectionState = {
        selectedCodes: new Set(['23', '36']), // Conflicting consultation levels
        conflicts: new Map([
          ['23', [{
            conflictingCodes: ['23', '36'],
            reason: 'category_exclusive_consultation',
            severity: 'blocking' as const,
            message: 'Cannot bill multiple consultation levels'
          }]]
        ]),
        totalFee: 121.75,
        warnings: ['Multiple consultation levels selected']
      };

      const config: ReportConfiguration = {
        type: 'consultation_summary',
        sections: {
          summary: true,
          codeDetails: false,
          conflicts: true,
          recommendations: false,
          evidence: false,
          billing: false
        },
        styling: { template: 'professional' }
      };

      const report = generateConsultationReport(
        conflictedSelectionState,
        mockRecommendations,
        mockConsultationNote,
        'general_practice',
        config
      );

      expect(report.sections.conflictAnalysis).toBeDefined();
      expect(report.sections.conflictAnalysis.hasConflicts).toBe(true);
      expect(report.sections.conflictAnalysis.blockingConflicts).toHaveLength(1);
      expect(report.sections.conflictAnalysis.warnings).toContain('Multiple consultation levels selected');
    });
  });

  describe('generateBillingAnalysisReport', () => {
    it('should generate comprehensive billing analysis', () => {
      const config: ReportConfiguration = {
        type: 'billing_analysis',
        sections: {
          summary: true,
          codeDetails: true,
          conflicts: true,
          recommendations: false,
          evidence: false,
          billing: true
        },
        styling: { template: 'professional' }
      };

      const report = generateBillingAnalysisReport(
        mockSelectionState,
        mockRecommendations,
        config
      );

      expect(report).toHaveProperty('title', 'Billing Analysis Report');
      expect(report).toHaveProperty('sections');
      expect(report.sections).toHaveProperty('billingBreakdown');
      expect(report.sections).toHaveProperty('feeAnalysis');
      expect(report.sections).toHaveProperty('categoryBreakdown');
    });

    it('should analyse fees by category', () => {
      const config: ReportConfiguration = {
        type: 'billing_analysis',
        sections: {
          summary: true,
          codeDetails: true,
          conflicts: false,
          recommendations: false,
          evidence: false,
          billing: true
        },
        styling: { template: 'detailed' }
      };

      const report = generateBillingAnalysisReport(
        mockSelectionState,
        mockRecommendations,
        config
      );

      expect(report.sections.categoryBreakdown).toBeDefined();
      
      const professionalAttendances = report.sections.categoryBreakdown.find(
        cat => cat.category === 'professional_attendances'
      );
      expect(professionalAttendances).toBeDefined();
      expect(professionalAttendances!.totalFee).toBe(41.20);
      expect(professionalAttendances!.codeCount).toBe(1);

      const diagnosticProcedures = report.sections.categoryBreakdown.find(
        cat => cat.category === 'diagnostic_procedures'
      );
      expect(diagnosticProcedures).toBeDefined();
      expect(diagnosticProcedures!.totalFee).toBe(35.30); // 19.80 + 15.50
      expect(diagnosticProcedures!.codeCount).toBe(2);
    });

    it('should provide fee optimisation suggestions', () => {
      const config: ReportConfiguration = {
        type: 'billing_analysis',
        sections: {
          summary: true,
          codeDetails: false,
          conflicts: false,
          recommendations: true,
          evidence: false,
          billing: true
        },
        styling: { template: 'professional' }
      };

      const report = generateBillingAnalysisReport(
        mockSelectionState,
        mockRecommendations,
        config
      );

      expect(report.sections.optimisationSuggestions).toBeDefined();
      expect(report.sections.optimisationSuggestions.potentialUpgrades).toBeDefined();
      expect(report.sections.optimisationSuggestions.additionalCodes).toBeDefined();
      expect(report.sections.optimisationSuggestions.estimatedIncrease).toBeGreaterThanOrEqual(0);
    });

    it('should calculate billing statistics', () => {
      const config: ReportConfiguration = {
        type: 'billing_analysis',
        sections: {
          summary: true,
          codeDetails: false,
          conflicts: false,
          recommendations: false,
          evidence: false,
          billing: true
        },
        styling: { template: 'simple' }
      };

      const report = generateBillingAnalysisReport(
        mockSelectionState,
        mockRecommendations,
        config
      );

      expect(report.sections.feeAnalysis).toBeDefined();
      expect(report.sections.feeAnalysis.totalFee).toBe(76.50);
      expect(report.sections.feeAnalysis.averageFeePerCode).toBe(25.50); // 76.50 / 3
      expect(report.sections.feeAnalysis.highestFeeCode).toBe('23');
      expect(report.sections.feeAnalysis.lowestFeeCode).toBe('57');
    });
  });

  describe('generateConflictReport', () => {
    it('should generate conflict analysis report', () => {
      const conflictedSelectionState: SelectionState = {
        selectedCodes: new Set(['23', '36']),
        conflicts: new Map([
          ['23', [{
            conflictingCodes: ['23', '36'],
            reason: 'category_exclusive_consultation',
            severity: 'blocking' as const,
            message: 'Cannot bill multiple consultation levels'
          }]]
        ]),
        totalFee: 121.75,
        warnings: ['Consultation level conflict detected']
      };

      const config: ReportConfiguration = {
        type: 'conflict_report',
        sections: {
          summary: true,
          codeDetails: true,
          conflicts: true,
          recommendations: true,
          evidence: false,
          billing: false
        },
        styling: { template: 'medical' }
      };

      const report = generateConflictReport(
        conflictedSelectionState,
        mockRecommendations,
        config
      );

      expect(report).toHaveProperty('title', 'Conflict Analysis Report');
      expect(report.sections).toHaveProperty('conflictSummary');
      expect(report.sections).toHaveProperty('detailedConflicts');
      expect(report.sections).toHaveProperty('resolutionSuggestions');
    });

    it('should detail all conflicts found', () => {
      const multipleConflictsState: SelectionState = {
        selectedCodes: new Set(['23', '36', '44']),
        conflicts: new Map([
          ['23', [{
            conflictingCodes: ['23', '36'],
            reason: 'category_exclusive_consultation',
            severity: 'blocking' as const,
            message: 'Cannot bill Level A and Level C together'
          }]],
          ['36', [{
            conflictingCodes: ['36', '44'],
            reason: 'category_exclusive_consultation',
            severity: 'blocking' as const,
            message: 'Cannot bill Level C and Level D together'
          }]]
        ]),
        totalFee: 242.30,
        warnings: ['Multiple consultation conflicts']
      };

      const config: ReportConfiguration = {
        type: 'conflict_report',
        sections: {
          summary: false,
          codeDetails: false,
          conflicts: true,
          recommendations: false,
          evidence: false,
          billing: false
        },
        styling: { template: 'detailed' }
      };

      const report = generateConflictReport(
        multipleConflictsState,
        mockRecommendations,
        config
      );

      expect(report.sections.detailedConflicts).toHaveLength(2);
      expect(report.sections.detailedConflicts.every(conflict => 
        conflict.severity === 'blocking'
      )).toBe(true);
    });

    it('should provide conflict resolution suggestions', () => {
      const conflictedState: SelectionState = {
        selectedCodes: new Set(['23', '36']),
        conflicts: new Map([
          ['23', [{
            conflictingCodes: ['23', '36'],
            reason: 'category_exclusive_consultation',
            severity: 'blocking' as const,
            message: 'Cannot bill multiple consultation levels'
          }]]
        ]),
        totalFee: 121.75,
        warnings: []
      };

      const config: ReportConfiguration = {
        type: 'conflict_report',
        sections: {
          summary: false,
          codeDetails: false,
          conflicts: false,
          recommendations: true,
          evidence: false,
          billing: false
        },
        styling: { template: 'professional' }
      };

      const report = generateConflictReport(
        conflictedState,
        mockRecommendations,
        config
      );

      expect(report.sections.resolutionSuggestions).toBeDefined();
      expect(report.sections.resolutionSuggestions).toHaveLength(1);
      expect(report.sections.resolutionSuggestions[0]).toHaveProperty('conflictingCodes');
      expect(report.sections.resolutionSuggestions[0]).toHaveProperty('suggestedAction');
      expect(report.sections.resolutionSuggestions[0]).toHaveProperty('reasoning');
    });
  });

  describe('generateRecommendationReport', () => {
    it('should generate comprehensive recommendation report', () => {
      const config: ReportConfiguration = {
        type: 'recommendation_report',
        sections: {
          summary: true,
          codeDetails: true,
          conflicts: true,
          recommendations: true,
          evidence: true,
          billing: false
        },
        styling: {
          template: 'professional',
          headerText: 'MBS Code Recommendations',
          footerText: 'AI-Generated Medical Coding Analysis'
        }
      };

      const report = generateRecommendationReport(
        mockRecommendations,
        mockConsultationNote,
        'general_practice',
        config
      );

      expect(report).toHaveProperty('title', 'MBS Code Recommendations');
      expect(report.sections).toHaveProperty('analysisOverview');
      expect(report.sections).toHaveProperty('recommendedCodes');
      expect(report.sections).toHaveProperty('evidenceAnalysis');
      expect(report.sections).toHaveProperty('confidenceAssessment');
    });

    it('should rank recommendations by confidence', () => {
      const config: ReportConfiguration = {
        type: 'recommendation_report',
        sections: {
          summary: false,
          codeDetails: true,
          conflicts: false,
          recommendations: true,
          evidence: false,
          billing: false
        },
        styling: { template: 'simple' }
      };

      const report = generateRecommendationReport(
        mockRecommendations,
        mockConsultationNote,
        'general_practice',
        config
      );

      expect(report.sections.recommendedCodes).toBeDefined();
      expect(report.sections.recommendedCodes).toHaveLength(3);
      
      // Should be sorted by confidence (highest first)
      expect(report.sections.recommendedCodes[0].confidence).toBe(0.95); // ECG
      expect(report.sections.recommendedCodes[1].confidence).toBe(0.9);  // Level A
      expect(report.sections.recommendedCodes[2].confidence).toBe(0.85); // BP monitoring
    });

    it('should include confidence assessment analysis', () => {
      const config: ReportConfiguration = {
        type: 'recommendation_report',
        sections: {
          summary: true,
          codeDetails: false,
          conflicts: false,
          recommendations: false,
          evidence: false,
          billing: false
        },
        styling: { template: 'detailed' }
      };

      const report = generateRecommendationReport(
        mockRecommendations,
        mockConsultationNote,
        'general_practice',
        config
      );

      expect(report.sections.confidenceAssessment).toBeDefined();
      expect(report.sections.confidenceAssessment.averageConfidence).toBe(0.9); // (0.95 + 0.9 + 0.85) / 3
      expect(report.sections.confidenceAssessment.highConfidenceCodes).toBe(3); // All above 0.8
      expect(report.sections.confidenceAssessment.lowConfidenceCodes).toBe(0);
      expect(report.sections.confidenceAssessment.recommendationQuality).toBe('High');
    });

    it('should analyse evidence strength', () => {
      const config: ReportConfiguration = {
        type: 'recommendation_report',
        sections: {
          summary: false,
          codeDetails: false,
          conflicts: false,
          recommendations: false,
          evidence: true,
          billing: false
        },
        styling: { template: 'medical' }
      };

      const report = generateRecommendationReport(
        mockRecommendations,
        mockConsultationNote,
        'general_practice',
        config
      );

      expect(report.sections.evidenceAnalysis).toBeDefined();
      expect(report.sections.evidenceAnalysis.totalEvidenceSpans).toBe(3);
      expect(report.sections.evidenceAnalysis.strongEvidence).toBeGreaterThan(0);
      expect(report.sections.evidenceAnalysis.coveragePercentage).toBeGreaterThan(0);
    });
  });

  describe('ReportingService class', () => {
    it('should generate reports and return formatted output', async () => {
      const config: ReportConfiguration = {
        type: 'consultation_summary',
        sections: {
          summary: true,
          codeDetails: true,
          conflicts: false,
          recommendations: false,
          evidence: false,
          billing: true
        },
        styling: { template: 'professional' }
      };

      const htmlReport = await reportingService.generateReport(
        mockSelectionState,
        mockRecommendations,
        mockConsultationNote,
        'general_practice',
        config,
        'html'
      );

      expect(htmlReport).toContain('<!DOCTYPE html>');
      expect(htmlReport).toContain('Medical Consultation Report');
      expect(htmlReport).toContain('<table');
      expect(htmlReport).toContain('ECG recording and report');
    });

    it('should generate PDF reports', async () => {
      const config: ReportConfiguration = {
        type: 'billing_analysis',
        sections: {
          summary: true,
          codeDetails: false,
          conflicts: false,
          recommendations: false,
          evidence: false,
          billing: true
        },
        styling: { template: 'professional' }
      };

      const pdfBlob = await reportingService.generateReport(
        mockSelectionState,
        mockRecommendations,
        mockConsultationNote,
        'general_practice',
        config,
        'pdf'
      );

      expect(pdfBlob).toBeInstanceOf(Blob);
      // Mock returns empty blob, so we check that it's defined
      expect(pdfBlob).toBeDefined();
    });

    it('should handle custom styling configurations', async () => {
      const config: ReportConfiguration = {
        type: 'consultation_summary',
        sections: {
          summary: true,
          codeDetails: true,
          conflicts: false,
          recommendations: false,
          evidence: false,
          billing: false
        },
        styling: {
          template: 'professional',
          headerText: 'Custom Medical Practice',
          footerText: 'Confidential Medical Document',
          logo: 'data:image/png;base64,customlogo...'
        }
      };

      const htmlReport = await reportingService.generateReport(
        mockSelectionState,
        mockRecommendations,
        mockConsultationNote,
        'specialist',
        config,
        'html'
      );

      expect(htmlReport).toContain('Custom Medical Practice');
      expect(htmlReport).toContain('Confidential Medical Document');
    });

    it('should validate report configurations', () => {
      const invalidConfig = {
        type: 'invalid_type',
        sections: {},
        styling: { template: 'unknown' }
      } as any;

      expect(() => {
        reportingService.validateConfiguration(invalidConfig);
      }).toThrow('Invalid report configuration');
    });

    it('should provide report templates', () => {
      const templates = reportingService.getAvailableTemplates();

      expect(templates).toContain('professional');
      expect(templates).toContain('medical');
      expect(templates).toContain('simple');
    });

    it('should estimate report generation time', () => {
      const config: ReportConfiguration = {
        type: 'recommendation_report',
        sections: {
          summary: true,
          codeDetails: true,
          conflicts: true,
          recommendations: true,
          evidence: true,
          billing: true
        },
        styling: { template: 'detailed' }
      };

      const estimatedTime = reportingService.estimateGenerationTime(
        mockSelectionState,
        mockRecommendations,
        config,
        'pdf'
      );

      expect(estimatedTime).toBeGreaterThan(0);
      expect(typeof estimatedTime).toBe('number');
    });
  });
});